### ISSUE TITLE
Work with Tobii Pro Glasses 3? Some issues following demo manual

### ISSUE THREAD

**Issue by shp0929** [dcnieho/GlassesViewer#8]
Hi, 

Our research team recently bought Tobii Pro Glasses 3 and I was wondering if GlassesViewer is compatible with Glasses 3. 

I was able to "Select Recording" on MATLAB. However, when selected recording was loaded, there was an error (see also picture attached) and the glassesViewer interface did not open. I am using MATLAB R2021b on a Windows 10.

Error in glassesViewer (line 239)
            hm.UserData.plot.defaultValueScale(:,a) = [max(nanmin(hm.UserData.data.eye.binocular.gp3(:)),-hm.UserData.settings.plot.gazePoint3DLim) min(nanmax(hm.UserData.data.eye.binocular.gp3(:)),hm.UserData.settings.plot.gazePoint3DLim)];

Thank you for your time
![Error](https://user-images.githubusercontent.com/95594455/144771952-c8f5dcb1-8086-48dc-9b22-a5acc69432a6.png)
.

**Comment by wangxin917** [comment]
> Hi,
> 
> Our research team recently bought Tobii Pro Glasses 3 and I was wondering if GlassesViewer is compatible with Glasses 3.
> 
> I was able to "Select Recording" on MATLAB. However, when selected recording was loaded, there was an error (see also picture attached) and the glassesViewer interface did not open. I am using MATLAB R2021b on a Windows 10.
> 
> Error in glassesViewer (line 239) hm.UserData.plot.defaultValueScale(:,a) = [max(nanmin(hm.UserData.data.eye.binocular.gp3(:)),-hm.UserData.settings.plot.gazePoint3DLim) min(nanmax(hm.UserData.data.eye.binocular.gp3(:)),hm.UserData.settings.plot.gazePoint3DLim)];
> 
> Thank you for your time ![Error](https://user-images.githubusercontent.com/95594455/144771952-c8f5dcb1-8086-48dc-9b22-a5acc69432a6.png) .
hi, have you resolved this problem?

**Comment by dcnieho** [comment]
@wangxin917 : are you running into the same issue? let me try to resolve it, there is no need for a toolbox for this function

**Comment by dcnieho** [comment]
I have resolved the use of nanmin, nanmax etc, if that was your issue. Note also that the code screenshot suggests this was a very old verions. @wangxin917, if you still have an issue with the latest code, please open a new report and show the error.

**Comment by wangxin917** [comment]
@dcnieho  Thanks so much for replying, my dear friend. I was not able to open the recording in the "demo_data>>projects" which exists in the downloaded  Glasses Viewer folder from this resource. Specifically, when I selected a recording by clicking the "demo_data>>projects" folder, there was no reaction and some errors were reported as seen in the picture attached.  I am using Matlab 2025b version  for Mac system. Do you know how to solve it ? By the way I feel so lucky to come across you ,because you are the only person I met who is also handling with Tobii Pro Glasses3 data. 

<img width="2882" height="1538" alt="Image" src="https://github.com/user-attachments/assets/e8e98792-ba30-4dba-a089-3eb92dafa610" />

**Comment by dcnieho** [comment]
@wangxin917 that's a different issue altogether than this report was about. The problem is that Matlab completely redesigned their UI using different technologies with R2025a. GlassesViewer cannot be supported in those technologies without a complete rewrite. You need to install R2024b or older. 

Cheers, 
Dee

**Comment by wangxin917** [comment]
@dcnieho Thanks, I will try as you said. In addition, I found that this version of Matlab on my computer failed to enable Java, possibly due to itself an uncompleted version with restricted functions.

**Comment by dcnieho** [comment]
Missing java is indeed the problem, with this matlab version, as all that was removed
